Config = {}
Config.Locale = 'en'

pedList = {
    'u_m_y_imporage',
    'g_m_y_salvagoon_01',
    'u_m_y_tattoo_01',
    's_m_y_xmech_02',
    'u_m_y_rsranger_01',
    's_m_y_mime',
    'ig_cletus',
    'ig_manuel',
    'ig_groom',
    'g_m_y_lost_01',
    'g_m_y_lost_02',
    'g_m_y_lost_03',
    'ig_clay',
    'ig_chef',
    'ig_terry',
    'skin_dante',
    'skin_dante2',
    'u_m_y_zombie_01',
    's_m_y_ammucity_01',
    's_m_y_dwservice_01',
    'a_f_m_trampbeac_01',
    'ig_lamardavis',
    'u_m_y_pogo_01',
    's_m_m_movspace_01',
    's_m_y_shop_mask',
    'ig_dale',
    'a_m_o_ktown_01',
    'a_c_mtlion',
    'a_c_pig',
    'a_c_cat_01',
    'a_c_shepherd',
    'a_c_husky',
    'a_c_coyote',
    'a_c_chop',
    'a_c_rottweiler',
    'a_c_westy',
    's_m_m_movalien_01',
    'ig_orleans',
}
